### ISSUE TITLE
Calling `.clear()` while elements are in the cache causes an exception when they are subsequently attempted to be purged as stale

### ISSUE THREAD

**Issue by fredkilbourn** [isaacs/ttlcache#17]
```
TypeError: this.expirations[exp] is not iterable
    at TTLCache.purgeStale (node_modules/@isaacs/ttlcache/index.js:204:41)
    at Timeout._onTimeout (node_modules/@isaacs/ttlcache/index.js:79:41)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
```
https://github.com/isaacs/ttlcache/blob/1fe77335fd4a13036af1fa7bd69d0e66267a8d86/index.js#L204

**Comment by fredkilbourn** [comment]
This may be related to https://github.com/isaacs/ttlcache/issues/16 where the internal state seems to be corrupted within my `dispose()` method and subsequently performing mutations on the collection from within it.
