### ISSUE TITLE
bug: deleting an immortal entry causes an error

### ISSUE THREAD

**Issue by StimulCross** [isaacs/ttlcache#18]
When I try to delete an immortal entry (set with `Infinity` TTL) I get the following error:

```
"C:\Program Files\nodejs\node.exe" C:\Dev\ttlcache\test.js
C:\Dev\ttlcache\index.js:164
        this.expirations[current] = exp.filter(k => k !== key)
                                        ^

TypeError: Cannot read properties of undefined (reading 'filter')
    at TTLCache.delete (C:\Dev\ttlcache\index.js:164:41)
    at Object.<anonymous> (C:\Dev\ttlcache\test.js:6:25)
    at Module._compile (node:internal/modules/cjs/loader:1149:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1203:10)
    at Module.load (node:internal/modules/cjs/loader:1027:32)
    at Module._load (node:internal/modules/cjs/loader:868:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.10.0

Process finished with exit code 1
```

Code to reproduce the issue:
```js
const TtlCache = require('@isaacs/ttlcache');
const cache = new TtlCache({ttl: Infinity});
cache.set('key', 'val');
cache.delete('key');
```

Entries with TTL set to `Infinity` is not present in the `expirations` object and the `exp` const can be `undefined` which causes the error.

So I fixed it and added a test for such a case. I will link a PR 🙃

**Comment by isaacs** [comment]
Fixed by #19
